#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2006-2007, TUBITAK/UEKAE
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# Please read the COPYING file.
#

import locale
import yali
import yali.sysutils
from yali.constants import consts

def try_umount_target():
    for mpoint in ("/home", "/dev", "/proc", "/sys", ""):
        yali.sysutils.umount(consts.target_dir + mpoint)

def main():
    try_umount_target()
    runner = yali.default_runner()
    runner.run()


if __name__ == "__main__":
    locale.setlocale(locale.LC_ALL, "")
# Buggy with gui code...
#     try:
#         import psyco
#         psyco.full()
#     except ImportError:
#         pass
    main()
