#!/usr/bin/python
# -*- coding: utf-8 -*-

import yali
import locale

def main():
    runner = yali.default_runner()
    runner.run()


if __name__ == "__main__":
    locale.setlocale(locale.LC_ALL, "")

    try:
        import psyco
        psyco.full()
    except ImportError:
        pass

    main()
